### ISSUE TITLE
Un front acceptable pour le jeu siouplé

### ISSUE THREAD

**Issue by hdurand-98** [arthur-trt/ft_transcendence#301]
Le jeu est jouable et fonctionnel mais pas tres joli, je vais rajouter des trucs pour le rendre plus agreable a l'oeil et equilibrer la vitesse de la balle et des raquettes

**Comment by arthur-trt** [comment]
<img src="https://media0.giphy.com/media/xT1R9LQ4S45QeHmzUA/giphy.gif"/>
